# Terminal beauty
alias ls='exa --icons'
alias la='ls -laa'
alias cd='>/dev/null cd'
alias neofetch='clear && nf'

# Text editors
alias nv='nvim'
alias hx='helix'

# Config files
alias nvcf='nv ~/.config/nvim/init.vim'
alias hxcf='hx ~/.config/helix/config.toml'

# Dotdrop
alias dotdrop='dotdrop --cfg=~/.dots/config.yaml'
# Your dotdrop git repository location
export DOTREPO="~/.dots"
#alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"
