# Terminal beauty
alias ls='exa --icons'
alias la='ls -laa'
alias cd='>/dev/null cd'
alias neofetch='clear && nf'

# Text editors
alias nv='nvim'
alias hx='helix'

# Config files
alias nvcf='nv ~/.config/nvim/init.vim'
alias hxcf='hx ~/.config/helix/config.toml'

# Dotdrop
export DOTREPO="~/.dots"
alias dotdrop="dotdrop --cfg=$DOTREPO/config.yaml"
alias dotgit="git -C $DOTREPO"
function dotsync() {
	dotgit add --all;
	dotgit commit -m "$1";
	dotgit push;
}

