config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  longkey: false
dotfiles:
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  d_helix:
    src: config/helix
    dst: ~/.config/helix
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_hyprv:
    src: config/HyprV
    dst: ~/.config/HyprV
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wlogout:
    src: config/wlogout
    dst: ~/.config/wlogout
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  f_zenburn.py:
    src: config/ranger/colorschemes/zenburn.py
    dst: ~/.config/ranger/colorschemes/zenburn.py
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_tmux.conf:
    src: config/tmux/tmux.conf
    dst: ~/.config/tmux/tmux.conf
  f_init.lua:
    src: config/nvim/init.lua
    dst: ~/.config/nvim/init.lua
  f_readme.md:
    src: config/nvim/README.md
    dst: ~/.config/nvim/README.md
  d_lua:
    src: config/nvim/lua
    dst: ~/.config/nvim/lua
profiles:
  archlinux:
    dotfiles:
    - f_bash_aliases
    - d_helix
    - d_neofetch
    - f_bashrc
    - d_hypr
    - d_hyprv
    - d_swaylock
    - d_waybar
    - d_wlogout
    - d_wofi
    - d_kitty
    - d_dunst
    - f_zenburn.py
    - f_rc.conf
    - d_rofi
    - f_tmux.conf
    - f_init.lua
    - f_readme.md
    - d_lua
