config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: absolute
  link_on_import: nolink
  longkey: false
dotfiles:
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  d_helix:
    src: config/helix
    dst: ~/.config/helix
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_hyprv:
    src: config/HyprV
    dst: ~/.config/HyprV
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wlogout:
    src: config/wlogout
    dst: ~/.config/wlogout
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_custom:
    src: config/nvim/lua/custom
    dst: ~/.config/nvim/lua/custom
  f_chadrc.lua:
    src: config/nvim/lua/custom/chadrc.lua
    dst: ~/.config/nvim/lua/custom/chadrc.lua
  d_configs:
    src: config/nvim/lua/custom/configs
    dst: ~/.config/nvim/lua/custom/configs
  f_highlights.lua:
    src: config/nvim/lua/custom/highlights.lua
    dst: ~/.config/nvim/lua/custom/highlights.lua
  f_init.lua:
    src: config/nvim/lua/custom/init.lua
    dst: ~/.config/nvim/lua/custom/init.lua
  f_mappings.lua:
    src: config/nvim/lua/custom/mappings.lua
    dst: ~/.config/nvim/lua/custom/mappings.lua
  f_plugins.lua:
    src: config/nvim/lua/custom/plugins.lua
    dst: ~/.config/nvim/lua/custom/plugins.lua
  f_readme.md:
    src: config/nvim/lua/custom/README.md
    dst: ~/.config/nvim/lua/custom/README.md
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  f_zenburn.py:
    src: config/ranger/colorschemes/zenburn.py
    dst: ~/.config/ranger/colorschemes/zenburn.py
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
profiles:
  archlinux:
    dotfiles:
    - f_bash_aliases
    - d_helix
    - d_neofetch
    - f_bashrc
    - d_hypr
    - d_hyprv
    - d_swaylock
    - d_waybar
    - d_wlogout
    - d_wofi
    - d_kitty
    - d_custom
    - f_chadrc.lua
    - d_configs
    - f_highlights.lua
    - f_init.lua
    - f_mappings.lua
    - f_plugins.lua
    - f_readme.md
    - d_dunst
    - f_zenburn.py
    - f_rc.conf
