[[language]]
name = "c"
file-types = ["c", "h"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "clang-format", args = ["--style=microsoft"] }
auto-format = true

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = [ "pylsp" ]
